language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
  
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug

  - psql -c 'CREATE DATABASE meals-test;' -U postgres

script:
  - npm run test

after_success:
  - npm run coverage
  - npm run coveralls
  - npm run report-coverage 
  - ./node_modules/.bin/mocha


install: npm install

services:
- postgresql

env:
- NODE_ENV=test
